# .github/workflows/deploy.yml

name: Terraform Deployment
on:
  push:
    branches: [ "main" ]
    paths: [ 'iac/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./iac

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="flask_secret_key=${{ secrets.FLASK_SECRET_KEY }}"
        working-directory: ./iac

      - name: Manual Approval for Deployment
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: ${{ github.actor }}
          minimum-approvals: 1
          issue-title: "Deploying Gym Management App to Production"

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="flask_secret_key=${{ secrets.FLASK_SECRET_KEY }}"
        working-directory: ./iac