name: IaC Security Scan
on: [push, pull_request]

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./iac
          output_format: sarif
          output_file_path: ./sast-scan-report/checkov.sarif